### ISSUE TITLE
Cannot scroll down in views on Android

### ISSUE THREAD

**Issue by ebma** [satoshipay/solar#1000]
Same as #960 but on Android.

There is a cordova preference which is useful in our case:
```
<preference name="resizeOnFullScreen" value="true" />
```
The [doc](https://github.com/ionic-team/cordova-plugin-ionic-keyboard#resizeonfullscreen-for-android-only) states that:
'There is an Android bug that prevents the keyboard from resizing the WebView when the app is in full screen (i.e. if StatusBar plugin is used to hide the StatusBar). This setting, if set to true, add a workaround that resizes the WebView even when the app is in full screen.' 
(Our app does not use the statusbar plugin but is running in full screen mode).

Unfortunately using this preference results in a black bar above the keyboard (see [here](https://github.com/ionic-team/cordova-plugin-ionic-keyboard/issues/132)) + the actions buttons on the bottom of the screen are slightly cut off. 

There seems to be a [working fix](https://github.com/ionic-team/cordova-plugin-ionic-keyboard/pull/134) for the black bar issue which is not merged yet.

So I'd suggest we wait until it is merged and add the preference afterwards or what would you think @andywer?

**Comment by andywer** [comment]
> There seems to be a working fix for the black bar issue which is not merged yet.
>
> So I'd suggest we wait until it is merged and add the preference afterwards or what would you think @andywer?

Sounds good 👍
