### ISSUE TITLE
v0.24.0 Open orders list is not updating on OSX Mac

### ISSUE THREAD

**Issue by tourBermuda** [satoshipay/solar#1003]
The orders list is not updating OSX Mac. If you quit, and restart the app loads the orders.  Also the  notifications panel is not displaying the description of the notification. It displays the  title, and the description says:
"offer-details.string"

![Screen Shot 2020-03-13 at 12 30 15 PM](https://user-images.githubusercontent.com/10064984/76638506-4b53be80-652b-11ea-936c-1a21ebd4df9b.png)

**Comment by andywer** [comment]
Thanks for reporting, @tourBermuda!

Almost looks like our QA process needs to be QA-ed… 😉

**Comment by tourBermuda** [comment]
@andywer any idea what would happen if I try to reinstall 0.23  until this is fixed. Will I loose any accounts from my current setup?

**Comment by andywer** [comment]
@tourBermuda The downgrade should work fine. If you want, I can also create a development build for you, since the issue should be fixed on latest `master`. Just let me know how I can send it to you if you're interested.

**Comment by tourBermuda** [comment]
@andywer I'm also on keybase as @tourbermuda. Maybe once your create the development build for OSX, you can put it in your keybase public folder. I can download it from there.

**Comment by andywer** [comment]
@tourBermuda Good idea! Done. <https://keybase.pub/andywer/>

**Comment by tourBermuda** [comment]
@andywer quick question, is the container/installer just a way to trigger a larger file download? The file is only 8KB and the v0.23 is 75MB file.

**Comment by andywer** [comment]
Are you sure? Looks like 81 MB at my machine 🤔

![image](https://user-images.githubusercontent.com/1842462/77782396-82f85580-7057-11ea-801e-2e1802395b55.png)

**Comment by tourBermuda** [comment]
@andywer I was going to https://keybase.pub/andywer/ and downloading from the web. what's strange is a (.dmg) container file was downloading which was 8K. (I never tried installing it though). Ok, thanks I'm,   downloading with the keybase  desktop app now.
