### ISSUE TITLE
Cannot proceed in 'Add funds' view

### ISSUE THREAD

**Issue by ebma** [satoshipay/solar#1042]
The 'Proceed' button stays disabled after entering a valid email address.

<img width="848" alt="Screenshot 2020-04-01 at 17 39 21" src="https://user-images.githubusercontent.com/6690623/78227311-5e740180-74cd-11ea-8713-6f1a72521728.png">

**Comment by andywer** [comment]
@ebma Are you using the latest version of Solar? It doesn't show any email address input when I try an anchorusd.com deposit using Solar v0.24.0.

**Comment by ebma** [comment]
I was using the latest master but I checked and it happens on Solar v.0.24.0 and I was using anchorusd USD token as well. I'm talking about the second screen, the one that appears after selecting 'USD' as 'Asset to deposit' and hitting 'Proceed'.

**Comment by andywer** [comment]
Ohhh, I have an idea! I was just preparing a screencast when I realized that maybe you still got an outdated stellar.toml for anchorusd.com cached in your local storage. Need to check if we update those in a timely manner…

**Comment by ebma** [comment]
Wow you're right, deleting the stellar.toml entry from local storage fixed it and now I'm not seeing the email address field anymore and can proceed.

But this still happens on my Solar Wallet desktop app (as I did not wipe the storage there like no user would do) I think we still have to do something about outdated cache values?

**Comment by ebma** [comment]
Closing this because it should be fixed by #1052.
