### ISSUE TITLE
Alert message not de-referenced correctly

### ISSUE THREAD

**Issue by ddombrowsky** [satoshipay/solar#1049]
The alert message that pops up when a transaction happens includes `offer-details.string` in it (or something like that.  I will get a screenshot the next time it happens.

I'm using `v0.24.0` on linux.

**Comment by ddombrowsky** [comment]
![Selection_470](https://user-images.githubusercontent.com/1651785/78585942-b03bc500-7808-11ea-8dbd-775f4835b3e5.png)

**Comment by ddombrowsky** [comment]
BTW I named the wallet `stellarport.io` in Solar Wallet, the alert isn't coming from the site.

**Comment by andywer** [comment]
Sorry that I didn't get back to your earlier, @ddombrowsky, and thanks for reporting!

One question, though: What do you mean by "not de-referenced correctly"? You mean that there are numerous notifications for one trade, I assume.

**Comment by ddombrowsky** [comment]
@andywer 
> One question, though: What do you mean by "not de-referenced correctly"? 

I assume the display is not supposed to read `offer-details.string`, but is actually supposed to be the string that is in `offer-details` (or something like that).  I haven't dug into the code, but my guess is whatever is generating this notification is referencing the javascript object, not the contents of the object.  

The fact that there are numerous notifications for one trade is not a problem.  It was probably multiple orders, so that is working as designed, I assume.

**Comment by andywer** [comment]
Ahh, it’s only about the message. That’s already been fixed, just waiting for the next release 😉
