### ISSUE TITLE
what's this

### ISSUE THREAD

**Issue by kof775** [satoshipay/solar#1050]
![S00407-175020](https://user-images.githubusercontent.com/61951234/78655199-413d9980-78f8-11ea-9d9a-5092f5d9092a.jpg)
when i take a payment and trust  asset
android 8.1
solar v 0.23   testnet

**Comment by andywer** [comment]
Hey @kof775!

> when i take a payment and trust asset

What's the exact steps you took and at what point did it happen?

Btw, try updating to v0.24.0 – maybe it's fixed already 😉

**Comment by kof775** [comment]
i use 0.23 is better  
0.24 is  bad  then  0.23

**Comment by andywer** [comment]
What issues do you have with v0.24?

**Comment by andywer** [comment]
Closing, due to inactivity. We need more details here.
