### ISSUE TITLE
Android: enabling fingerprint lock fails w/ BIOMETRIC_DISMISSED

### ISSUE THREAD

**Issue by bdlow** [satoshipay/solar#1077]
Solar app installed from Google Play store; v0.24.0 on a Pixel 3a Android 10 build QQ2A.200405.005

When I attempt to enable Fingerprint lock, the app pops up the same "Confirm" dialog twice in succession, followed by two fingerprint unlocks, and results in the Fingerprint lock being disabled and a red "BIOMETRIC_DISMISSED" message at the bottom of the app.

Repro:
- Install the app from the Play store
- open the app (no accounts configured)
- open settings (gear icon)
- toggle Fingerprint lock
- dialog pops up: Confirm; Unlock your device once to enable the feature. Cancel OK
- click OK
- same dialog pops back up
- in quick succession: a Android Unlock Solar fingerprint dialog pops up, goes away, the BIOMETRIC_DISMISSED message flashes, and a second Android Unlock dialog appears
- doesn't matter whether you apply the fingerprint or cancel, you're returned to the settings page, Fingerprint lock is disabled

Repeatable: 100%

**Comment by ebma** [comment]
Hey @bdlow, thank you very much for your detailed bug report! 
I was able to reproduce your issue and will start working on a fix soon.
