### ISSUE TITLE
0.25.1 OSX, open orders trasaction, is not updating

### ISSUE THREAD

**Issue by tourBermuda** [satoshipay/solar#1093]
@andywer  just started using 0.25.0 OSX, desktop client (updated from 0.23). The open orders transactions section is not  updating.  I am using MacOS Sierra, could that be the problem? This was working in 0.23

**Comment by tourBermuda** [comment]
False alarm it seems to be working now. This may be an intermittent   problem. I'll update tomorrow and close  this if it's fine.

**Comment by andywer** [comment]
Hey @tourBermuda!

I got an email notification where you stated that it was a false alarm. Did you delete the comment again – is it confirmed now?

We tested those live updates quite a bit before we released v0.25.0. Kind of disappointing to see that you are still encountering issues 😕 

We will definitely check that out! Not sure if we can still fit it in the v0.25.1 release, though.

**Comment by andywer** [comment]
PS: Is there any way to reliably reproduce the issue or does it happen sporadically only?

**Comment by tourBermuda** [comment]
@andywer I'm do multiple small transactions and trades per week. Give me a few days and I can give your a definitive answer.  if there is also an issue on the  recent transaction section I'll let you know. The recent transaction seems to be working today. However I've sent two trades  since 2020-05-26 19:31:18 UTC, they are still open at 19:53:47 and I still don't see anything in the client.

**Comment by tourBermuda** [comment]
Recent transaction is working ok.  However This problem with the open order updating, has been present for about a month. I admit It's most likely something to do with my OSX version. However since this a great entry level wallet, I think it should support a good range of OS versions.
