### ISSUE TITLE
How to install to Linux?

### ISSUE THREAD

**Issue by superclarkk** [satoshipay/solar#1106]
There are no instructions for installing to linux / Ubuntu, and I don't recognise any of the files extensions in [releases](https://github.com/satoshipay/solar/releases/tag/v0.25.2).  Could someone explain?

**Comment by ebma** [comment]
Hey @superclarkk, thanks for pointing this out! 
We actually had some trouble with creating the linux builds and they were missing in the current release but we added them now so please have a look again. You can choose between `.AppImage`, `.deb`, `.rpm` or `.snap`. 
Let me know if you need further assistance.

**Comment by superclarkk** [comment]
On Ubuntu 18.04, the .AppImage file works well. Thank you.
