### ISSUE TITLE
SatoshiPay Horizon Sever 504 error

### ISSUE THREAD

**Issue by tourBermuda** [satoshipay/solar#1117]
@andywer  The  SatoshiPay Horizon Sever is not responding. Is there anyway to temporary switch the Horizon server that the desktop client looks for. Maybe I can change a config file on OSX?

**Comment by tourBermuda** [comment]
@andywer is there anyway to put SolarWallet into offline mode. I need to extract some wallet keys that were not backed up to a text file. Of course the App is still failing with a 504 error on open. So the UI is loading. I'm on OSX desktop  and I do have access the app files.

**Comment by andywer** [comment]
Hey @tourBermuda. We have been facing some technical issues with our horizon servers in the last few days, but we are on it.

> is there anyway to put SolarWallet into offline mode

At first I didn't understand your issue, but I tried myself and I see your point: Unfortunately, if the account does not load, then the account settings icon button is not shown either… This is something we can fix, though. Let me open another issue for that.

**Comment by andywer** [comment]
See #1118.
