### ISSUE TITLE
APK requires Android SDK version 21

### ISSUE THREAD

**Issue by bjorn** [satoshipay/solar#1134]
On my Jolla phone it will not install, because the APK requires Android SDK version 21, whereas my phone only supports up to 19.

Since most Android software manages to work on my phone, are you sure you need the more recent version? Just hoping this may be an oversight.

**Comment by andywer** [comment]
Hey @bjorn. I am not the Android-savvy one here (rather @ebma), but I just checked and the latest Android SDK version is 29. So it seems we already support 8 (!) legacy major versions.

I don't know all the details out of the back of my head, but that seems perfectly reasonable. Time to upgrade 😉

**Comment by bjorn** [comment]
@andywer Hmm, upgrading means buying a new device, which I don't plan to do for several more years since it is working fine.

I really hope somebody will check whether there's actually some critical API needed between version 21 and 19 that you couldn't lower the required SDK version a bit. :-(

**Comment by andywer** [comment]
Sorry, but those old SDK versions have definitely reached their end of life.

**Comment by bjorn** [comment]
Based on choosing Android 21 vs. 19 as the minimum you're causing 4% of Android users to not be able to install your app:

![image](https://user-images.githubusercontent.com/531764/89991230-d0323800-dc83-11ea-97d1-18a59c39029a.png)
([source](https://www.xda-developers.com/android-version-distribution-statistics-android-studio/))

Android 4.4 has definitely not reached "end of life" if there's still 4% of people using it, but why it that even a criteria? By Google's own words in the screenshot above, you'll want to choose your minimum SDK version _as low as possible_, only raising it _if you need features_ from a more recent version.

That's why I was asking whether you really needed some features of SDK 21, or whether it could be lowered to 19.

**Comment by ebma** [comment]
Hey @bjorn, the main reason why our apk requires Android API level 21 is because the secure storage plugin we use requires Android API level 21 or above (see [here](https://github.com/crypho/cordova-plugin-secure-storage#android)). Although it states that one could use an older version to support lower API levels we decided not to do so because of the overall low benefit and security considerations.

**Comment by andywer** [comment]
Thanks, @ebma!
To make it short: We don't have the resources to keep our app compatible with several-years-old legacy APIs.

If your phone is older than four or five years, then incompatibilities have to be expected. If it's not that old, just update. If it's not that old yet and you cannot update anymore, you might wanna sue your manufacturer 😉

Btw, after that amount of time you most likely don't receive any security updates anymore, either. In that case I would not recommend storing any secret keys on it 🙊

**Comment by bjorn** [comment]
@ebma Thank you so much for the in-depth explanation! It makes it a lot easier to accept that my phone won't be able to run Solar.

@andywer While my phone is compatible with Android up to version 4.4, it actually runs SailfishOS and does still receive security updates. Of course I'm very careful about installing software in general anyway. To store cryptocurrency I also rely on the TREZOR hardware wallet so I don't actually need to trust my phone to keep that safe.

Thanks again for checking and I'm sorry that I got a little agitated with the response based on the version's age.

**Comment by andywer** [comment]
No worries, @bjorn.

I got a bit worked up, too – Android tends to do that with me 😅
