### ISSUE TITLE
Allow importing pubnet/testnet account with same key

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#1140]
We currently prevent importing an account if we already have an account with the same key. We should only do so for matching accounts on the same network.

Labelling this as a bug, as Torsten got quite confused by the current behavior and found it highly unintuitive (even sent me a screenshot with the form error and one with his empty pubnet account list). Will likely affect other users the same way.

**Comment by andywer** [comment]
@ebma I distantly recall a quick discussion we had about something like that some while ago. Don't know why we had it or what the outcome was, though.

**Comment by ebma** [comment]
Hmm yes I think I do remember but maybe the discussion was more related to #1010 because it is a quite similar issue (the part about duplicate account names). 
But right now I don't see issues with doing so.
