### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by ddombrowsky** [satoshipay/solar#1170]
```
Cannot read property 'toLowerCase' of undefined
```

When loading the asset list of an account on the testnet.  I don't know how to get the stack trace.  

I then need to close the app and reload it to get it working again.  Prevents me from adding an asset to an account.

This is on TESTNET.

Running version `v0.25.3`
on 
`Linux phydeaux3 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by andywer** [comment]
Thanks for reporting, @ddombrowsky!

Seems like this issue has already been fixed by #1155. Sorry to say it hasn't been rolled out yet, but we are going to release very soon!

@ebma Let's target a release next week.

**Comment by ddombrowsky** [comment]
tyvm
