### ISSUE TITLE
Co-signing requests only shown if account exists

### ISSUE THREAD

**Issue by andrenarchy** [satoshipay/solar#1171]
Pending co-signing requests only seem to be shown on accounts that exists on the chain. However, an account is not necessary to sign and submit.

**Comment by andywer** [comment]
Hey André! True, but this is still the old multi-signature implementation which, unfortunately, does require that.

This quirk will go away once #1114 lands which is currently still blocked by externalities. Not for much longer, though, I hope.

**Comment by andywer** [comment]
Status: Wait for new multi-sig implementation that is pretty much done already 😉
