### ISSUE TITLE
bug: handleConnectionState prevents restoration of online from offline

### ISSUE THREAD

**Issue by ngault** [satoshipay/solar#1180]
In `connection.ts`, the `if` conditions on lines 28 and 31 are the same.  Presumably, "app:pause" on line 31 should be "app:resume". 

``` typescript
export function handleConnectionState(handlers: ConnectionStateHandlers) {
  const { onOffline = () => undefined, onOnline = () => undefined } = handlers

  const handleMessage = (event: MessageEvent) => {
    if (event.data && event.data === "app:pause") {
      onOffline()
    } else if (event.data && event.data === "app:pause") {
      onOnline()
    }
  }
```

https://github.com/satoshipay/solar/blob/b59bc02e15f12b442f553be10bd6b1aea06a54f4/src/Workers/lib/connection.ts#L25

**Comment by andywer** [comment]
Hey Nick. Great catch!

@ebma Can you quickly prepare a PR?
