### ISSUE TITLE
App crash when deleting account name

### ISSUE THREAD

**Issue by efarid** [satoshipay/solar#1192]
Steps to reproduce:
From home screen > Add account > Create Account > (Delete account name)
or
From existing account > Account settings > (Delete account name)

Error Message:
Oops, something went wrong...
undefined is not an object (evaluating 'w.accountCreation.name')

OS version: iOS 14.3
App version: 0.25.3

**Comment by ebma** [comment]
Thank you very much for your detailed bug report! It really helped fixing the issue.

**Comment by efarid** [comment]
You're welcome. Thanks a lot for the fix 👍
