### ISSUE TITLE
Fetch error when accessing lumen details page

### ISSUE THREAD

**Issue by ebma** [satoshipay/solar#1194]
An error is thrown when navigating to the lumen details page which makes the app crash when trying to return to the previous screen. While trying to reproduce on testnet I always encountered a `"Failed to fetch"` error originating from [useTickerAssets()](https://github.com/satoshipay/solar/blob/f9bf1f628545a5ab580ad913ef7af9e97308f8a0/src/Generic/hooks/stellar-ecosystem.ts#L12).
```
Access to fetch at 'https://ticker-testnet.stellar.org/assets.json' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

<img src="https://user-images.githubusercontent.com/6690623/102771501-49eed680-4386-11eb-8b3a-d55fb6387f47.jpg" alt="19271" width="300px">

**Comment by ebma** [comment]
Seems like this issue does not exist anymore. Maybe SDF changed something that broke the ticker service and fixed it again.

**Comment by andywer** [comment]
Great! (That it's already fixed)

Maybe they just suffered from a temporary service outage. If the service is down, it cannot send the CORS headers either, oftentimes leading to a CORS error cascading the actual issue.
