### ISSUE TITLE
Multi-signature transaction fails on testnet

### ISSUE THREAD

**Issue by ebma** [satoshipay/solar#1196]
An error occurs when trying to send a transaction to the multi-signature endpoint. (Only happens on account with multiple signers and required signatures >1). 

Seems like the multi-sig endpoint is having some issues.
<img width="613" alt="Screenshot 2021-01-06 at 09 47 30" src="https://user-images.githubusercontent.com/6690623/103748690-caf3d200-5004-11eb-9cdd-d67c46ffdbb1.png">

**Comment by ddombrowsky** [comment]
I get "Multi-signature connection issue" every time I load the app now, both on testnet and mainnet.

**Comment by andywer** [comment]
@ddombrowsky Should be fixed now. We updated the multi-sig service and fixed its deployment yesterday 👍
