### ISSUE TITLE
Trading error unclear if automatic price calculation fails

### ISSUE THREAD

**Issue by ebma** [satoshipay/solar#1215]
When trying to create a new order with the price set to 0.00 a "Couldn't find approximation" error is shown which does not really help the user identify the problem. This often happens when Solar is not able to automatically calculate a price for the asset pair. 

Expected: 
Highlight and expand the 'price' input field when clicking on "Place order" with a price of 0.00 and show an improved error message like 'Invalid price set'.

**Comment by Craddock7** [comment]
Yes every app needs a way to liquidate on the same site
