### ISSUE TITLE
Merge or Delete Account

### ISSUE THREAD

**Issue by hellojoechip** [satoshipay/solar#1237]
"Are you sure you want to delete account" in the dialog should make it clear: are we talking about actually 'deleting' the Stellar account? Or just removing it from the config of the Solar Wallet app?

**Comment by ebma** [comment]
Hey @hellojoechip do you think this would already make it clear enough? Or do you think we should add a more detailed explanation?

<img width="797" alt="Screenshot 2021-04-28 at 14 47 16" src="https://user-images.githubusercontent.com/6690623/116407099-ae88d900-a831-11eb-8774-fab036187d25.png">

**Comment by hellojoechip** [comment]
looks good!

**Comment by hellojoechip** [comment]
In Keybase, the confirmation dialog will say "This removes [account] from Keybase, but you can still use it elsewhere if you save the private key". Cancel/Yes, remove

**Comment by andywer** [comment]
@ebma Can you please open a PR? With your proposed change and maybe add a Keybase-ish "You can still use the account if you save the secret key" note.
