### ISSUE TITLE
Problem entering price at: Trade / Sell / Advanced

### ISSUE THREAD

**Issue by marcoachury** [satoshipay/solar#1251]
I noted this on 0.27.0

Fail to validate keyboard entry on Trade/Sell/Advanced...  May be related with spanish locale, not clear if decimal separator is "." or ","

![imagen](https://user-images.githubusercontent.com/67766219/118915236-396d6880-b8f2-11eb-92be-23570594ea41.png)

![imagen](https://user-images.githubusercontent.com/67766219/118915424-8bae8980-b8f2-11eb-8d14-4cc5ca10e209.png)

**Comment by ebma** [comment]
Hello @marcoachury, are you encountering an error that says something like "Invalid price" above the price input field? If so, your issue is related to #1248 and will be fixed in the next release.

**Comment by marcoachury** [comment]
No, I didn't proceed, I will not risk to lost money on an invalid operation.  I simply note strange prices are accepted by the app.
