### ISSUE TITLE
multisignature not working with Lobster Vault

### ISSUE THREAD

**Issue by metheis** [satoshipay/solar#1254]
Hello, I enabled multisignature collective signing in my Solar Wallet with two required: the wallet itself and a lobster vault I have setup. When I set this up, the Lobster Vault app showed a notification it had been added as a multisigner, great! However, whenever I try to make a transaction, I do not get a notification in Lobster Vault to sign the transaction. Solar Wallet shows it is waiting for the signer, but I do not get notified. Moreover, the transaction does not show up in Lobster Vault. Am I missing something here? Is there a way I can manually view the transaction XDR so I can manually sign in Lobster Vault?

**Comment by metheis** [comment]
Thank you, that was it. I didn't realize I needed to add the bystander public key for LOBSTR.

**Comment by D4vid-A** [comment]
@metheis Hello, I currently have the same problem as you, how did you get out of this ?
Cannot add the GA2T6GR7VXXXBETTERSAFETHANSORRYXXXPROTECTEDBYLOBSTRVAULT key because I can't sign any transaction... Did you find a way to get the transaction XDR from Solar Wallet ?
