### ISSUE TITLE
How to remove trust chain on actives with very little balance.

### ISSUE THREAD

**Issue by marcoachury** [satoshipay/solar#1274]
When an active have very low balance (near zero) is impossible to trade it because the decimal rounding.  Also is impossible to remove trust chain.  Is a problem from the wallet or from the stellar protocol?  The solution I think is to create a "carity" account that receive any remaining balance from people that want to close accounts.

![imagen](https://user-images.githubusercontent.com/67766219/133658620-7ee06503-4b20-4ed2-9438-5db2dea28d72.png)

**Comment by ebma** [comment]
Hey @marcoachury, you can always get rid of the assets you have by sending the remaining balance to the asset issuer. This way you don't have to have another account that holds the assets you don't want anymore.
If you want to remove the BRAVE assets from your account just send the `0.0000041` BRAVE to `GDREF4TAC3RFYVLHEV24CXN2VBGCEEP74BZOC3T4Q4XJ6SXJFMDPNTJL`, i.e. the issuer of the BRAVE token which you can find by clicking on the BRAVE item in the "Assets & Balances" view in Solar. It is listed underneath "Issuing Account".
