### ISSUE TITLE
Add auto updater

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#173]
See <https://www.npmjs.com/package/electron-updater>.

**Comment by erasmus** [comment]
Let's make this a top priority after getting developer account

**Comment by andywer** [comment]
@erasmus Thought about it, too, and tried to quickly add the electron-builder auto-updater last night.

Turns out it doesn't work out-of-the-box seamlessly, because it uses the intended filename when building the application, but puts another filename in the update metadata file, so the updater will never be able to find the actual application... 🙃

See electron-userland/electron-builder#2706.

**Comment by andywer** [comment]
Well, it's hacky, but with [a custom hook](https://www.electron.build/configuration/configuration#afterallartifactbuild) one might be able to patch the YAML file into shape after its creation / before publishing with little effort.
