### ISSUE TITLE
Better account activation call-to-action

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#296]
As a first-time user I create a new (mainnet) account and then I am lost and don't know where to go / what to do with my 0 XLM account.

Show some options where usually the transaction history would be:

- Coinbase
- Moonpay
- Kraken
- Send money from different account (just link to "receive")

## TBD

- What services/exchanges to show? -> Coordinate with @erasmus and @litodertechie

**Comment by litodertechie** [comment]
Very good idea. I did some research and came up with this list:

-  Coinify (https://www.coinify.com/deposits/) they just added XLM
-  Shapeshift 
- Moonpay.io  (https://www.moonpay.io/)
<img width="1440" alt="Bildschirmfoto 2019-07-11 um 11 04 58" src="https://user-images.githubusercontent.com/30246668/61038403-4901f900-a3cd-11e9-9fa2-a980572f400c.png">

**Comment by litodertechie** [comment]
There's also Coinbase connect, which let's you open a coinbase account & buy crypto within the wallet or signup to coinbase if you don't have an account yet.
https://developers.coinbase.com/docs/wallet/coinbase-connect/integrating
