### ISSUE TITLE
Make sure that UI works on mobile devices

### ISSUE THREAD

**Issue by Marcel-Ebert** [satoshipay/solar#385]
## Left to do (2019-04-02)

- [x] MainTitle wrapping & font-size (#468)
- [ ] Account page
  - [ ] Balances in one line
- [x] Send payment: Use `<MainTitle>`
- [x] Tx confirmation dialog:
  - [ ] Full-screen
  - [ ] Use `<MainTitle>`
  - [ ] Font-sizes
- [ ] ~~Move main action buttons to bottom & make sticky on mobile~~ (moved to #467)

**Comment by Marcel-Ebert** [comment]
Transactions appearing in the SignatureRequestList can not be reviewed or dismissed.

Probably because these options only appear when hovering above them, which is not possible on mobile(?)

**Comment by Marcel-Ebert** [comment]
In "Receive Funds" dialog copying the text to clipboard by clicking on it does not work.
`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'navigator.clipboard.writeText')
https://stellar-horizon-testnet.satoshipay.io/accounts/GDESJFVIMGWZQQI33YPTGKZ6PBNTNFY5FVVLTVBGMSK3TTQMPT3CQOZJ?c=0.8019324937122966`

The hint could be removed on mobile versions because the user is able to long press on the text and copy it by himself or the clipboard can be accessed via [Cordova Clipboard Plugin](https://www.npmjs.com/package/cordova-clipboard).

**Comment by andywer** [comment]
> Transactions appearing in the SignatureRequestList can not be reviewed or dismissed.

Can't you tap on the item to trigger the hover state? 🤔

> copying the text to clipboard by clicking on it does not work

Good point! Let's create a `clipboard.ts` file in `src/platform`, shall we?

**Comment by Marcel-Ebert** [comment]
> Can't you tap on the item to trigger the hover state? 

It's strange. It does not seem to work at all on iOS Simulator but it worked sometimes on a physical android device although it was kind of buggy. If you click on the right side of the element you instantly select the option beneath it before seeing it and afterwards clicking on it seems to be disabled for some time. 

> Let's create a clipboard.ts file in src/platform, shall we?

Sure, let's use the Cordova Clipboard Plugin then.

**Comment by Marcel-Ebert** [comment]
Space between ListItem text and balance might be too big (?)

![simulator screen shot - iphone 8 - 2019-03-04 at 15 23 02](https://user-images.githubusercontent.com/6690623/53742481-fbaed180-3e98-11e9-9a6a-5e0655c3fedb.png)

**Comment by andywer** [comment]
@Marcel-Ebert Regarding the tx confirmation dialog: Try to make it fullscreen (w/ MainTitle) for both mobile and desktop and check how it looks, esp. on desktop.

Maybe we can easily have a decent looking solution here, otherwise we should talk to Daniel and might need to keep it non-fullscreen on desktop for the time being.

**Comment by andywer** [comment]
Closing. Last remaining point (balances in one line) is now covered by #687.
