### ISSUE TITLE
Show desktop notification on incoming payment

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#420]
Might wanna ignore super small payments though as a kind of spam protection (?)

**Comment by andywer** [comment]
@erasmus Do you like the idea? We have almost everything we'd need for that already in place anyway.

**Comment by erasmus** [comment]
I like. However, there should be a way to turn it off in global Settings. Wouldn't worry too much about amount size atm.

**Comment by andywer** [comment]
Some context about the size: There used to be those frequent unsolicited txs, sending super tiny amounts to you, with a memo luring you to some spammy website.

That's what I think should be filtered. The amount just seemed to be the lowest-hanging fruit as a criterion.

**Comment by erasmus** [comment]
What would be the filter threshold? I've seen spam txs of e.g. `0.00057XLM`. 

Still, I'd argue that this should be optional feature (on by default).
