### ISSUE TITLE
Improve form error handling

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#488]
- Investigate if there is a cool React form validation library using hooks

Otherwise just do this:
- Add `FormError(message: string, fieldErrors?: { [fieldName: string]?: Error }): Error`
- Add `FormFieldError(fieldName: string, message: string): Error`
- Throw and catch them when validating
- Validate form fields on blur already

**Comment by ebma** [comment]
We are using `react-hook-form` for form error handling now.
