### ISSUE TITLE
Adjust style of <OfferList> to support smaller screens

### ISSUE THREAD

**Issue by Marcel-Ebert** [satoshipay/solar#522]
The style of the `<OfferList>` component needs to be revised because currently the text of the balances and currency conversion info overlap on small screens.

Maybe try to make it wrap its children or think of another lean solution.

**Comment by andywer** [comment]
Looks like this right now:

![Screenshot_2019-04-23-15-53-30-139_io solarwallet](https://user-images.githubusercontent.com/1842462/56671665-54d6fc80-66b5-11e9-9a26-c5f5358a3e7d.png)

**Comment by Marcel-Ebert** [comment]
Closed by #579.
