### ISSUE TITLE
Cannot go back on tx submission error

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#527]
Would need to click on background to close, but dialog is too big on mobile. As reported by Sebastian.

**Comment by herrhelms** [comment]
My Idea here was to show a more verbose `← Try again` (or "Go back") link on top, once any error occurs - maybe even with a short delay. The solution above (clicking the background to close) might stop me from fully reading and understanding the actual error if I tap on the bg by accident too fast. just my 2cts 😆

**Comment by andywer** [comment]
Hey @herrhelms! Welcome to the repo 😊

I was just stating the status quo in the description. Completely agree, we need an explicit way to go back! 🔙
