### ISSUE TITLE
Show electron update notification longer

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#560]
In `electron/lib/updater.js`: Set ~~[`requireInteraction`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification#Parameters) option on desktop notification~~ (edit: it's an [electron notification](https://electronjs.org/docs/api/notification), not a web desktop notification) to keep the notification open until the user dismisses it.

Also add a query parameter `?download=false` to the URL when opening the "downloading..." page. This is just a pre-caution in case we make the page initiate a download in the future.

**Comment by Marcel-Ebert** [comment]
According to [this](https://github.com/electron/electron/issues/9283) electron issue ticket, the `requireInteraction` parameter is not working and labeled as `wontfix` for now. 

But maybe we could use [node-notifier](https://www.npmjs.com/package/node-notifier) for notifications, it claims to be working cross-platform and has a `wait`-parameter.

**Comment by andywer** [comment]
Sorry, I was wrong about one aspect: It's not a web desktop notification. I updated the description.

There doesn't seem to be an easy fix for the electron notifications either, though...

**Comment by andywer** [comment]
In case of doubt: Just implement the second part of the story.

**Comment by andywer** [comment]
Putting this on hold for now, since there are no low-hanging fruits to be found here.

**Comment by andywer** [comment]
Closing for now. See #673 instead.
