### ISSUE TITLE
Make open orders collapsible

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#564]
As reported by @erasmus: Open offers eat quite a bit of prime real estate… could we maybe have a little down/up caret that shows/hides it?

Should also allow loading more than latest 10 orders.

![image (2).png](https://images.zenhubusercontent.com/59ccc62eb0222d5de4797771/e9b4011c-135f-44df-830e-dfe0d9040b91)

**Comment by ddombrowsky** [comment]
I would like to 2nd this.  It might also provide a way for the UI to display ALL orders for the account, not just the first 10 returned.

**Comment by andywer** [comment]
Completely agree. Updated the issue description.

Cannot give an estimate on when this story might be worked on, though.
