### ISSUE TITLE
Android Backbutton navigates too far back when clicked in past transaction view

### ISSUE THREAD

**Issue by Marcel-Ebert** [satoshipay/solar#618]
The Android back button navigates to the main menu when clicked in a detailed transaction view. 
It should actually navigate back to the account overview.

**Comment by andywer** [comment]
@Marcel-Ebert Feel free to look into this. Only easy fixes for now, since we might want to refactor the whole back button navigation anyway (tbd).

**Comment by Marcel-Ebert** [comment]
Closed by #695.
