### ISSUE TITLE
Android: transaction list glitch

### ISSUE THREAD

**Issue by s-a-y** [satoshipay/solar#649]
Hey,
Observing multiple duplicates of the same transaction in transaction list

1. Created new account
2. Funded with 5 XLM
![photo_2019-07-10_09-36-05](https://user-images.githubusercontent.com/1667781/60946247-67e18c00-a2f6-11e9-95c2-ae35836bbb1a.jpg)
3. Added trustline to KIN
![photo_2019-07-10_09-36-06](https://user-images.githubusercontent.com/1667781/60946253-6adc7c80-a2f6-11e9-84f2-84e9289e8b55.jpg)
4. Went out of my account to the list and then back into my account
![photo_2019-07-10_09-36-06 (2)](https://user-images.githubusercontent.com/1667781/60946256-6dd76d00-a2f6-11e9-94a0-dacd17ac771d.jpg)

OS: Android 9.

Let me know if you need more details

**Comment by Marcel-Ebert** [comment]
Hey @s-a-y, thanks for you report.
Are the duplicates still shown after closing and re-opening the application?

**Comment by s-a-y** [comment]
No, of course not.

**Comment by andywer** [comment]
Thanks for reporting this, @s-a-y, we are looking into it. Or Marcel is, since I am on vacation.

@Marcel-Ebert Check out [`src/subscriptions/recent-txs.ts`](https://github.com/satoshipay/solar/blob/master/src/subscriptions/recent-txs.ts):

In line 48 and following we should have a check like
```ts
if (subscriptionTarget.getLatest().transactions.map(tx => createCheapTxID(tx)).indexOf(createCheapTxID(deserializedTransaction)) === -1)
```
