### ISSUE TITLE
DEX UI Issue - iOS

### ISSUE THREAD

**Issue by koltenb** [satoshipay/solar#672]
![DEX-Issue](https://user-images.githubusercontent.com/14185460/62136821-82ca6f00-b2aa-11e9-8dcb-33e29021b74a.png)

**Solar Wallet - iOS**

I currently have two USD assets (one has a balance of 0). When trying to select one to trade on the DEX it seems like the menu is freezing up and 'selecting' both. Was unable to find a way around it but can confirm the interface works fine on Windows - so it seems to be an iOS thing. 

I tested on another account with two USD assets to be sure and had the same issue.

**Comment by andywer** [comment]
Thanks for reporting, Kolten :)

We will look into it!
