### ISSUE TITLE
Add NGNT and EURW to asset list

### ISSUE THREAD

**Issue by litodertechie** [satoshipay/solar#699]
NGNT: https://stellar.expert/explorer/public/asset/NGNT-GAWODAROMJ33V5YDFY3NPYTHVYQG7MJXVJ2ND3AOGIHYRWINES6ACCPD

EURW: https://stellar.expert/explorer/public/asset/EURW-GBZQW42YNBVYKLHR43WU6DGGYQ3WBV6DQEGCG3PGWSASMIKUY2BA5KUU

**Comment by andywer** [comment]
Will tackle those independently, as discussed.
