### ISSUE TITLE
Add LOBSTR Vault support

### ISSUE THREAD

**Issue by ebma** [satoshipay/solar#703]
We should integrate LOBSTR Vault support.

Actions:
- [ ] Show a LOBSTR Vault icon for accounts that contain the public signer key
- [ ] Send the signed transactions to the LOBSTR endpoint
- [ ] Add LOBSTR Vault icon (?)

(see for more info: https://github.com/Lobstrco/Vault-Android#developers-integrate-lobstr-vault-with-your-service)

**Comment by Marcel-Ebert** [comment]
@pitsevich Does Lobstr Vault have a testnet endpoint? And if it does, is it the same as for the mainnet endpoint?

**Comment by pitsevich** [comment]
@Marcel-Ebert No, we don't support testnet currently!

**Comment by pitsevich** [comment]
We have recently upgraded our icons, so if you'll need a Vault icon, it's best to use this svg:
https://github.com/stellarterm/stellarterm/blob/master/images/sign-vault.svg

**Comment by andywer** [comment]
Thanks for the update, @pitsevich!

**Comment by ebma** [comment]
Hey @pitsevich, do you have an outlined version of the Vault icon by chance?
I used the one you mentioned but it does not really fit well as we mostly use outlined icons.
<img width="683" alt="Screenshot 2020-04-21 at 15 28 55" src="https://user-images.githubusercontent.com/6690623/79871639-ee2e1100-83e4-11ea-80e7-7cd321dc894a.png">

**Comment by pitsevich** [comment]
@ebma Hey. Sure, we've prepared these options, I hope it will look good in the app.: ![vault examples](https://user-images.githubusercontent.com/984711/79983218-19316700-84b0-11ea-9ec9-f829113a3e4f.png)

See attached zip archive: [vault logos.zip](https://github.com/satoshipay/solar/files/4516135/vault.logos.zip)

**Comment by ebma** [comment]
@pitsevich those icons seem great. Could you maybe provide them as '.svg' files as well? 🙂

**Comment by pitsevich** [comment]
@ebma Sure, here you are.
[icons svg.zip](https://github.com/satoshipay/solar/files/4539340/icons.svg.zip)

**Comment by krudder64** [comment]
How do I completely remove all signers from vault and expert

**Comment by ebma** [comment]
Hi @krudder64, if you have questions regarding your multi-signature setup with LOBSTR vault please consider reaching out to either us (hello@solarwallet.io) or LOBSTR via mail. This issue is not the right place for that.
