### ISSUE TITLE
Try KeyboardShrinksView in cordova config

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#790]
See <https://cordova.apache.org/docs/en/3.0.0/guide/platforms/ios/config.html>. Might feel more natural than what we have right now? Looks a bit weird when the keyboard appears on iOS.

**Comment by Marcel-Ebert** [comment]
@andywer the doc you linked is from version 3.0.0 and pretty outdated.
The `KeyboardShrinksView` preference does not seem to exist in the latest version anymore.

I tried a similar method from the plugin that we are using already (https://www.npmjs.com/package/cordova-plugin-keyboard#keyboardshrinkview) but I didn't have much success, it still jumped when hiding the keyboard and introduced some weird layout issues e.g. in the inflation destination dialog the textfield label just merged with the actual textfield, don't ask me why.

I found out that with disabling our iphone notch fix the jumping disappeared. But I know again why we introduced it in the first place: 
When the keyboard disappears, a white gap remains below the actual screen content and that's how we got rid of it.
