### ISSUE TITLE
Error toasts are cut off

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#813]
Trim the error message cleanly with an ellipsis ("…") and allow opening the full error message in a dialog when you click on the error toast.

Also very valuable to be able to open the error, so it does not auto-hide after a few seconds.

**Comment by Marcel-Ebert** [comment]
@andywer do we only want to show the dialog with the message for error notifications or for notifications in general? 
If we made every notification clickable + opening a dialog we could circumvent problems with cut off notification messages as well.

**Comment by andywer** [comment]
@Marcel-Ebert I don't think we have a real use case for that. I think "Network connectivity issues" & "Copied to clipboard" are more or less all other notifications we have.
