### ISSUE TITLE
Sending funds requires a walletframe

### ISSUE THREAD

**Issue by BouweCeunen** [satoshipay/solar#819]
Hi,

Sending funds requires a walletframe, I cannot seem to find what this is?

**Comment by andywer** [comment]
Hey @BouweCeunen. Please excuse the delayed response to your issue!

I do not understand what you mean. Where did you see the words "Wallet frame"? Sounds like it may be part of some app error message.

**Comment by BouweCeunen** [comment]
After clicking on the 'send now' button a new screen appeared with the 'walletframe' text in red and an input box in red also, suggesting it needed to be filled. I did an iOS update and it seems to be resolved. Not sure if the iOS update resolved it or not but it seems to be gone now.

**Comment by andywer** [comment]
Yeah, sounds very much like a bug. If it should happen again, can you please take a screenshot? That would be super helpful for debugging.

Closing for now. And thanks for reporting!
