### ISSUE TITLE
[iOS] Asset search result list is cut off after closing keyboard

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#820]
I think I have a good fix already: Using [`cordova-plugin-ionic-keyboard`](https://github.com/ionic-team/cordova-plugin-ionic-keyboard) instead of `cordova-plugin-keyboard` with the following config:

```xml
    <preference name="KeyboardResize" value="true" />
    <preference name="KeyboardResizeMode" value="body" />
```

(And dropping the `Keyboard.shrinkView(true)` line from `app.cordova.ts`)

**Comment by andywer** [comment]
@Marcel-Ebert Seems to work fine with an iPhone 8. Can you try and see if using the other plugin impacts Android in any way? The config is iOS-only.

**Comment by andywer** [comment]
Pushed my changes to branch [`bugfix/820-alt-cordova-keyboard-plugin`](https://github.com/satoshipay/solar/tree/bugfix/820-alt-cordova-keyboard-plugin).

**Comment by Marcel-Ebert** [comment]
@andywer I tested it and it does not seem to do any harm.

But unrelated to this I noticed that the action buttons are covering some input fields as they did on iOS. 
We probably should think about hiding the action buttons when the keyboard is visible not only on iOS but on mobile in general.

**Comment by andywer** [comment]
@Marcel-Ebert Sounds good! Try changing this line: https://github.com/satoshipay/solar/blob/master/src/theme.ts#L296

**Comment by Marcel-Ebert** [comment]
@andywer I added this change to a separate PR (#824) as it is unrelated to this issue. 😬
