### ISSUE TITLE
loadUrl(file:///android_asset/www/index.prod-android.html)

### ISSUE THREAD

**Issue by rajisundaram-s** [satoshipay/solar#849]
Unable to open asset URL: file:///android_asset/www/index.prod-android.html

**Comment by andywer** [comment]
Hey, thanks for sharing. That doesn't sound good! ...

Can you provide some more information?

- Version of Solar you are running
- What device do you use
- Android version
- Did you launch the app for the first time or did it work before?

This kind of community feedback is super important to us. Thank you 🙂

**Comment by rajisundaram-s** [comment]
Create the development build:
npm run dev:android
when run above code not working
but build in production build working fine
I fixed the above issue

**Comment by andywer** [comment]
> I fixed the above issue

How did you fix it?

**Comment by rajisundaram-s** [comment]
fixed when create build using -> npm run build:android

**Comment by rajisundaram-s** [comment]
can i remove XLM currency

**Comment by andywer** [comment]
> can i remove XLM currency?

See #850.
