### ISSUE TITLE
Sometimes empty blue window on Mac after opening link

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#869]
Tansel reported:

With every approx. 8th click on the stellar explorer link (hash) of a transaction I get this blue screen. Need to restart Solar. I can reproduce (Mac OS Catalina, Solar v0.22.1-pre).

Update to Version 0.22.1 (0.22.1): approx. every ~~5th~~ 3rd click gets a blue screen.

![image](https://user-images.githubusercontent.com/1842462/69819692-b9d07300-11ff-11ea-8e93-01b1b0e37521.png)

**Comment by andywer** [comment]
Seems fairly well reproducable if dev tools are not open. Not reproducable when dev tools are open. Smells like a race condition...

Check if #823 "accidentally" fixes this issue.

**Comment by ebma** [comment]
I tested it on the branch of #823 and it seems like the issue does not occur there.
Might be related to using `shell.openExternal(href)` instead of `window.open` on that branch. 

So this issue should be resolved when we merge #823.

**Comment by ebma** [comment]
I tested it again on the latest version of our master branch since #823 is merged by now and clicking the transaction hash (>10 times) does not lead to a blue screen. (Tested on Mac OS Catalina)

So this issue seems to be fixed.
