### ISSUE TITLE
Prepare for i18n: Replace hard-coded strings

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#876]
Replace all hard-coded strings in the UI by a call to a translation function `t()` that looks up the localized string from a JSON object (hard-coded for now) that maps translation keys to translated messages.

Create a React hook to obtain the translation function `t()`, stick to the API of <https://react.i18next.com/latest/usetranslation-hook>, so we can easily switch to i18next or another i18n solution later.

## To be defined

- Do we already need i18next for parameter substitution in strings?

**Comment by andywer** [comment]
@ebma Still need to settle on a naming scheme for the translation keys. I propose something like `page.settings.biometric.title.ios` for the TouchID/FaceID app setting's title.

**Comment by ebma** [comment]
Few examples:
`all-accounts`-page: 
- `all-accounts.switch-to.pubnet.short`
- `all-accounts.switch-to.testnet.long`

`trading`-dialog:
- `trading.title`
- `trading.place-order.label`

common:
- `common.ok.label`
- `common.cancel.label`

**Comment by andywer** [comment]
Done, except for some last places that are covered in #1008.
