### ISSUE TITLE
Fingerprint fallback PIN does not work on Android

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#879]
As reported by Tansel:

With the latest beta on a fairly new Huawei Mate 20 device (Android 9) you can opt-in to the PIN code fallback, but you cannot use the PIN to unlock - you will only see the fingerprint dialog again.

Works with an older Samsung S7 Edge and the latest Solar beta.

Might be an issue with our code, but there is a fair chance that the updated fingerprint plugin is to blame.

**Comment by ebma** [comment]
I tested it on emulator devices (Pixel 3 API Android 9.0, Pixel C API Android 9.0, Nexus 5X API Android 10) and was not able to reproduce. As there are only emulator images available for Google devices maybe we should consider asking Tansel if we can borrow his device for a second.

**Comment by andywer** [comment]
Works now according to Tansel. Closing for now. Let's re-open it if someone else reports something similar.
