### ISSUE TITLE
Path payment transaction breaks the wallet

### ISSUE THREAD

**Issue by Khlilo98** [satoshipay/solar#890]
After trying path payment, the source and destination accounts can't be loaded into solar wallet (Importing their private keys to solar).
You get an error saying: XDR Read Error: Unknown OperationType member for value 13.
I think the path payment transaction cannot be read in "recent transaction" by the wallet and it breaks it. 
https://prnt.sc/qcqh9w

**Comment by Khlilo98** [comment]
Just to be clear, if accounts have been involved in a path payment operation, they can never be loaded into solar.

**Comment by andywer** [comment]
Hey @Khlilo98. Wow, that’s an interesting bug and rather critical!

Can you share the account ID of one of those accounts, please?

I guess / hope the bug can be fixed by just updating the Stellar SDK version in our code. Anyway, such an error should not render the whole account unusable…

**Comment by Khlilo98** [comment]
Hey,
Thanks for responding back!

Here's the account address:
GC3QIJ5DIXOC7IZ72NGRFEM2BOJRJH46O7WFQJQXSEY7Q3NCXR4I6SKP
and here's the transaction that made the address unusable on solar :
https://stellar.expert/explorer/public/tx/117385695332438016#117385695332438017

Stellarterm had the same issue yesterday, I tried path payment by making a sell order on their platform, the trading page of the assets broke also:
https://github.com/stellarterm/stellarterm/issues/651#issuecomment-567409329

They fixed it in a few hours.

I could give the private key of the account, I'm using it for testing.

**Comment by Khlilo98** [comment]
And don't forget you have two operations for Path Payment:
- Path Payment Strict Send
- Path Payment Strict Receive

**Comment by meany** [comment]
@andywer, it looks like the update to the the latest SDK fixed the issue. We merged the latest into our fork (https://github.com/DinaroTN/wallet) and can now see path payments:

![Screenshot_20191227-225851](https://user-images.githubusercontent.com/854996/71534202-24da9b80-28cb-11ea-8606-baea03a5854f.png)

**Comment by andywer** [comment]
Thanks for sharing, @meany! Also nice to see the fork in action.

We will look into it after the holidays. Still need to make sure that a single unparseable tx doesn’t crash the whole view 💣 

Or maybe you are able to contribute a PR? 😉

**Comment by meany** [comment]
I'll try. I'm not well versed in React.

Since the SDK has been updated I would have to revert to get this issue to appear again. I agree that, going forward, it's possible for the SDK to add additional operation types and crash the view and there should be some type of "unable to read this transaction" type of message.

**Comment by ebma** [comment]
Closing this because #1115 should prevent crashes due to unparseable transaction and #1087 updated the stellar sdk.
