### ISSUE TITLE
Wrong quantity displayed on Recent transactions

### ISSUE THREAD

**Issue by batfab** [satoshipay/solar#891]
[I am totally new on GitHub, I hope this report is correctly placed here and with this format]
![buy and sell rates](https://user-images.githubusercontent.com/59267487/71493452-134bb200-283f-11ea-834e-285690e02856.jpg)
![buy and sell rates - detail](https://user-images.githubusercontent.com/59267487/71493523-8bb27300-283f-11ea-877c-1e447268369e.jpg)

It seems that the quantity of XLM going to be sold in order to buy EURT is wrongly calculated. Instead, it is correctly displayed on Open orders.

This happened in Testnet, I don't know if it happens in public too.

**Comment by andywer** [comment]
Thanks a lot for reporting, @batfab! We will definitely look into this issue.

**Comment by andywer** [comment]
Seems to still be broken (or broken again?)

**Comment by ebma** [comment]
I tested it with some orders and didn't see any wrong quantities. Maybe it was kind of related to #1092.
So I guess we can close this again.
