### ISSUE TITLE
Should we split the translation file?

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#948]
Right now we have one big JSON file containing all the English messages only. It is already > 600 lines long. I think I argued before to "chop down the messages file once it becomes too big".

We might be approaching that point sooner than I thought… So here is my idea:

How about having one central messages file containing all the generic messages and then have translation files in `src/components/*/<lang>.json`?

Pro:
- Organizational structure is better scalable

Con:
- ?

Left to figure out:
- A way how to glue all those JSON fragments back to together into one global translations object without having to replicate all the imports from the component directories for each language

@ebma

**Comment by ebma** [comment]
You are probably right that we should split them but I'm not sure if it's better to put them into the `i18n/<lang>/*.json` directory or into the components directories.
Let's decide once #945 is merged.
