### ISSUE TITLE
SEP-7 link handling doesn't seem to work

### ISSUE THREAD

**Issue by tomquisel** [satoshipay/solar#950]
I'm using Solar Wallet v. 0.23.0 on Mac OS 10.15.3. Solar is associated with SEP-7 links, but when I click one, all that happens is that Solar opens. It does not prompt me to sign & submit the transaction represented by the link.

For example: web+stellar:pay?amount=1&destination=GDBHV6PSN6F75PWFIHOKQSZVKWXWXXKBMLQN5KCYFK4CNXADZ62ANLJ3

**Comment by andywer** [comment]
Hey Tom!

Yes, that’s "correct" – well, known behavior for the time being. The feature hasn’t officially been released yet, the implementation is not complete, but we already merged parts of the code to avoid merge conflicts. The protocol handler is already in place and the the actual handling of the SEP-7 URI will follow in the next couple of weeks.
Hope we didn’t cause too much confusion 😉

**Comment by tomquisel** [comment]
Ok, cool! Closing it out then 😄
