### ISSUE TITLE
Improve key store init error handling on mobile

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#997]
We are pretty sloppy when it comes to key store init errors…

<https://github.com/satoshipay/solar/blob/d71e8273f52c5704e9c12f273b8580a81b744e7a/src/cordova/app.cordova.ts#L167-L178>

**Comment by andywer** [comment]
@ebma Is that PIN / unlock pattern error actually still a thing or did we forget to clean that up? 🤔

**Comment by ebma** [comment]
I think we forgot cleaning up. I actually saw this error sometimes when testing on an android emulator and was wondering why.
